### ISSUE TITLE
Agent 구성을  Only Java로 가져갈 것인가? JVMTI를 도입할 것인가? 

### ISSUE THREAD

**Issue by jth2246** [cest-tout/Remora#1]
###  Agent 구성에 관한 이슈 ### 

- C++ 도입 시 JNI Call로 인한 Overhead의 한계점
- Agent가 죽었을 때 영향 --> 그럼에도 OOM Dection에 용이하다. 
- Heap 메모리 덜 사용한다. 
- GraphQL의 구현체를 어디에서 적용할 것인가.

**Comment by fpnuseis** [comment]
OOM Detection이란 Feature의 중요도에 대해 고민해볼 것
C++로 구현시 JVMTI의 ResourceExhausted callback을 통해 OOM을 확인할 수 있고,
Logging 정도의 동작은 수행할 수 있을 것으로 보임

이 이상의 깊은 분석은 여전히 heap dump 분석을 요할 것으로 보임

**Comment by cest-tout** [comment]
### 2019-04-22 회의 결과
- OOM detection을 제외한 JVMTI의 기능은 BCI로 구현할 수 있음
- 순수하게 JVMTI로만 agent를 구현하는 것은 성능상의 문제가 있음
- BCI (ASM)를 이용하여 Java로 구현하기로 결정함
