### ISSUE TITLE
Remora 프로젝트 구조 논의

### ISSUE THREAD

**Issue by fpnuseis** [cest-tout/Remora#6]
여러 모듈, 여러 언어로 구성된 프로젝트의 경우
모듈별로 폴더를 따로 구성하는 것이 일반적이나, 본 프로젝트의 특수성으로 인해 논의가 필요하다.

## 레포지토리 구성
Agent 모듈의 경우 논리적으로 독립적이고 언어 또한 유일하게 Java이기 때문에 따로 구성한다.
Master, UI 모듈간 논의가 필요하다.

**모듈별로 폴더를 따로 구성할 경우**
-  Master 모듈과 UI 모듈 간 언어가 동일(js)하여, package.json 파일 및 node_modules 폴더를 공유한다. 따라서 Master와 UI를 분리할 경우 package.json 파일을 더 상위레벨에 위치시키거나 따로 관리해야한다.

**Master, UI를 같은 위치에 구성할 경우**
- 같은 package.json 파일 및 node_modules 폴더 사용으로 같은 파일이 중복되어 관리될 필요가 없다.
- 모듈에 대한 개념 측면에서는 완전히 다른 모듈이기 때문에 합리적인지 고려가 필요하다.

## 배포 파일 구성

**Agent**
- Agent는 jar 파일의 형태로 배포될 예정

**Master, UI**
- Master 모듈의 경우([링크](https://blog.outsider.ne.kr/1379)) 실행 파일의 형태로 생성 가능하다.
- 하지만 UI의 경우 Client에서 바로 Master로 요청을 보내고 Master가 바로 index.html을 반환하기 때문에 배포 형태에 대한 논의가 필요해 보임 -> *Master, UI는 배포시에 분리되어야하는가*
- Master가 직접 index.html을 반환하기 때문에(WAS에 웹앱을 올리는 형태가 아니기 때문에) War 패키징도 필요해 보이지 않음

**Comment by cest-tout** [comment]
[Heroku에 Node.js+MongoDB App 배포하기](https://advenoh.tistory.com/6)
위에 링크에 따르면, Heroku로 배포한다면 Node.js 앱을 binary 형태로 만들 필요는 없는 것 같습니다.
github의 target branch (우리는 master?)만 설정하면 자동으로 배포되더라구요!

**Comment by cest-tout** [comment]
## 2019-05-24 회의 결과
### 레포지토리 구성
- 모듈 별로 폴더를 따로 구성
- Master와 UI는 동일한 `package.json`을 공유
  - `package.json`는 프로젝트 최상단에 위치
- `index.html`은 UI 모듈에 포함
  - Master 모듈에서 linking 해서 사용

### 배포 파일 구성
- Heroku를 이용하여 Github과 TravisCI를 연동하여 배포
- 위 comment의 [링크](https://github.com/cest-tout/remora/issues/6#issuecomment-493948813) 참조
